---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffe-shop-front
  labels:
    app: coffe-shop-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coffe-shop-front
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: coffe-shop-front
    spec:
      
      containers:
        - name: coffe-shop-front
          image: coffe-shop-front
          imagePullPolicy: Never
          ports:
            - containerPort: 8100
          
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8100
            initialDelaySeconds: 10
            periodSeconds: 10
          
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8100
            initialDelaySeconds: 10
            periodSeconds: 60

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
        
---
apiVersion: v1
kind: Service
metadata:
  name: coffe-shop-front
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: coffe-shop-front
  type: LoadBalancer